(specifications->manifest
 '("python@3.10.7"
   "python-pyyaml"
   "python-statsmodels"
   "python-numpy"
   "python-scipy"
   "python-matplotlib"
   "python-pandas"
   "gcc-toolchain"
   "coreutils"
   "vim"
   "make"
   "bash"
   ))
