import random
import math
import copy
import yaml
import argparse

from Queue import BisectedPriorityQueue
from Host import Host
from Network import Network

class Sim:
    def __init__(self, config):
        self.network = Network(config['Simulation']['hosts'], config['Network'])

        self.hosts = [Host(i, self.network, config, self) for i in range(config['Simulation']['hosts'])]
        self.entities = self.hosts + [self.network]
        self.messages = []

        # Timestep counter
        global time
        time = 0

        # Initial ID to assign to new entries generated by the sendmsg function
        self.id = 0

        # Number of time steps to simulate for
        self.timeSteps = config['Simulation']['cycles']

    '''
    Iterate through simulation steps up to the max simulation time
    ''' 
    def simulate(self):
        for t in range(self.timeSteps):
            self.step()
            global time 
            time += 1

    def step(self):
        # Simulate all of the agents for this timestep
        random.shuffle(self.entities)
        for entity in self.entities:
            entity.tick()

        self.sweep()

    def sweep(self):
        for message in self.messages:
            if message.receiverReceived == message.length and message.endTime == 0:
                message.endTime = time

    def completeMessages(self, host):
        return [m for m in self.messages if m.src == host.id and m.endTime != 0]

    def avgCmplTime(self, host):
        complete = self.completeMessages(host)
        sumDir = 0
        for entry in complete:
            sumDir += (entry.endTime - entry.startTime)
         
            return sumDir / len(complete)

    def dumpStats(self):
        for host in self.hosts: 
            print(f'Host: {host.id} Statistics:')
            print(f'   - Total Complete Messages    : {len(self.completeMessages(host))}')
            print(f'   - Avg. Cmpl. Time            : {self.avgCmplTime(host)}')
            # print(f'   - Msg / Unit Time   : {self.msgThroughput(time)}')

    # The message throughput at the current time "time"
    # def msgThroughput(self, time):
    #     return len(self.messages) / time

    # # Average message completion time at the current time
    # def avgCmplTime(self):
    #     sumDir = 0
    #     complete = [m for m in self.messages if m.endTime != 0]
    #     for entry in complete:
    #         sumDir += (entry.endTime - entry.startTime)
    #         
    #     return sumDir / len(complete)

    # def dumpStats(self):
    #     print(f'Host: {self.id} Statistics:')
    #     print(f'   - Total Messages    : {len(self.messages)}')
    #     print(f'   - Avg. Cmpl. Time   : {self.avgCmplTime()}')
    #     print(f'   - Msg / Unit Time   : {self.msgThroughput(time)}')


def main(args):
    with open(args.config) as file:
        config = yaml.safe_load(file)

    sim = Sim(config) 
    sim.simulate()
    sim.dumpStats()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', type=str, help="yaml config file")

    args = parser.parse_args()

    main(args)


