// Generated by CIRCT firtool-1.62.0
// VCS coverage exclude_file
module mem_16384x82(
  input  [13:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [81:0] R0_data,
  input  [13:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [81:0] W0_data
);

  reg [81:0] Memory[0:16383];
  reg        _R0_en_d0;
  reg [13:0] _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 82'bx;
endmodule

module addr_map(
  input          clock,
                 reset,
  output         io_new_dma_map_i_ready,
  input          io_new_dma_map_i_valid,
  input  [63:0]  io_new_dma_map_i_bits_pcie_addr,
  input  [15:0]  io_new_dma_map_i_bits_port,
  input  [1:0]   io_new_dma_map_i_bits_map_type,
  output         io_dma_w_meta_i_ready,
  input          io_dma_w_meta_i_valid,
  input  [63:0]  io_dma_w_meta_i_bits_pcie_write_addr,
  input  [511:0] io_dma_w_meta_i_bits_data,
  input  [7:0]   io_dma_w_meta_i_bits_length,
  input  [15:0]  io_dma_w_meta_i_bits_port,
  output         io_dma_w_data_i_ready,
  input          io_dma_w_data_i_valid,
  input  [63:0]  io_dma_w_data_i_bits_pcie_write_addr,
  input  [511:0] io_dma_w_data_i_bits_data,
  input  [7:0]   io_dma_w_data_i_bits_length,
  input  [15:0]  io_dma_w_data_i_bits_port,
  output         io_dma_r_req_i_ready,
  input          io_dma_r_req_i_valid,
  input  [63:0]  io_dma_r_req_i_bits_pcie_read_addr,
  input  [9:0]   io_dma_r_req_i_bits_cache_id,
  input  [19:0]  io_dma_r_req_i_bits_message_size,
  input  [11:0]  io_dma_r_req_i_bits_read_len,
  input  [19:0]  io_dma_r_req_i_bits_dest_ram_addr,
  input  [15:0]  io_dma_r_req_i_bits_port,
  input          io_dma_w_req_o_ready,
  output         io_dma_w_req_o_valid,
  output [63:0]  io_dma_w_req_o_bits_pcie_write_addr,
  output [511:0] io_dma_w_req_o_bits_data,
  output [7:0]   io_dma_w_req_o_bits_length,
  output [15:0]  io_dma_w_req_o_bits_port,
  input          io_dma_r_req_o_ready,
  output         io_dma_r_req_o_valid,
  output [63:0]  io_dma_r_req_o_bits_pcie_read_addr,
  output [9:0]   io_dma_r_req_o_bits_cache_id,
  output [19:0]  io_dma_r_req_o_bits_message_size,
  output [11:0]  io_dma_r_req_o_bits_read_len,
  output [19:0]  io_dma_r_req_o_bits_dest_ram_addr,
  output [15:0]  io_dma_r_req_o_bits_port
);

  reg  [1:0]   new_dma_map_i_reg_0_bits_map_type;
  reg  [15:0]  new_dma_map_i_reg_0_bits_port;
  reg  [63:0]  new_dma_map_i_reg_0_bits_pcie_addr;
  wire [81:0]  _metadata_maps_ext_R0_data;
  wire [81:0]  _c2h_data_maps_ext_R0_data;
  wire [81:0]  _h2c_data_maps_ext_R0_data;
  wire [81:0]  _GEN =
    {new_dma_map_i_reg_0_bits_map_type,
     new_dma_map_i_reg_0_bits_port,
     new_dma_map_i_reg_0_bits_pcie_addr};
  reg  [63:0]  dma_w_meta_i_reg_0_bits_pcie_write_addr;
  reg  [511:0] dma_w_meta_i_reg_0_bits_data;
  reg  [7:0]   dma_w_meta_i_reg_0_bits_length;
  reg  [15:0]  dma_w_meta_i_reg_0_bits_port;
  reg  [63:0]  dma_w_meta_i_reg_1_bits_pcie_write_addr;
  reg  [511:0] dma_w_meta_i_reg_1_bits_data;
  reg  [7:0]   dma_w_meta_i_reg_1_bits_length;
  reg  [15:0]  dma_w_meta_i_reg_1_bits_port;
  reg          dma_w_meta_i_reg_0_valid;
  reg          dma_w_meta_i_reg_1_valid;
  reg  [63:0]  dma_w_data_i_reg_0_bits_pcie_write_addr;
  reg  [511:0] dma_w_data_i_reg_0_bits_data;
  reg  [7:0]   dma_w_data_i_reg_0_bits_length;
  reg  [15:0]  dma_w_data_i_reg_0_bits_port;
  reg  [63:0]  dma_w_data_i_reg_1_bits_pcie_write_addr;
  reg  [511:0] dma_w_data_i_reg_1_bits_data;
  reg  [7:0]   dma_w_data_i_reg_1_bits_length;
  reg  [15:0]  dma_w_data_i_reg_1_bits_port;
  reg          dma_w_data_i_reg_0_valid;
  reg          dma_w_data_i_reg_1_valid;
  reg  [63:0]  dma_r_req_i_reg_0_bits_pcie_read_addr;
  reg  [9:0]   dma_r_req_i_reg_0_bits_cache_id;
  reg  [19:0]  dma_r_req_i_reg_0_bits_message_size;
  reg  [11:0]  dma_r_req_i_reg_0_bits_read_len;
  reg  [19:0]  dma_r_req_i_reg_0_bits_dest_ram_addr;
  reg  [15:0]  dma_r_req_i_reg_0_bits_port;
  reg  [63:0]  dma_r_req_i_reg_1_bits_pcie_read_addr;
  reg  [9:0]   dma_r_req_i_reg_1_bits_cache_id;
  reg  [19:0]  dma_r_req_i_reg_1_bits_message_size;
  reg  [11:0]  dma_r_req_i_reg_1_bits_read_len;
  reg  [19:0]  dma_r_req_i_reg_1_bits_dest_ram_addr;
  reg  [15:0]  dma_r_req_i_reg_1_bits_port;
  reg          dma_r_req_i_reg_0_valid;
  reg          dma_r_req_i_reg_1_valid;
  reg          new_dma_map_i_reg_0_valid;
  wire         _GEN_0 = new_dma_map_i_reg_0_bits_map_type == 2'h0;
  wire         _GEN_1 = new_dma_map_i_reg_0_bits_map_type == 2'h1;
  always @(posedge clock) begin
    dma_w_meta_i_reg_0_bits_pcie_write_addr <= io_dma_w_meta_i_bits_pcie_write_addr;
    dma_w_meta_i_reg_0_bits_data <= io_dma_w_meta_i_bits_data;
    dma_w_meta_i_reg_0_bits_length <= io_dma_w_meta_i_bits_length;
    dma_w_meta_i_reg_0_bits_port <= io_dma_w_meta_i_bits_port;
    dma_w_meta_i_reg_1_bits_pcie_write_addr <= dma_w_meta_i_reg_0_bits_pcie_write_addr;
    dma_w_meta_i_reg_1_bits_data <= dma_w_meta_i_reg_0_bits_data;
    dma_w_meta_i_reg_1_bits_length <= dma_w_meta_i_reg_0_bits_length;
    dma_w_meta_i_reg_1_bits_port <= dma_w_meta_i_reg_0_bits_port;
    dma_w_meta_i_reg_0_valid <= io_dma_w_meta_i_valid;
    dma_w_meta_i_reg_1_valid <= dma_w_meta_i_reg_0_valid;
    dma_w_data_i_reg_0_bits_pcie_write_addr <= io_dma_w_data_i_bits_pcie_write_addr;
    dma_w_data_i_reg_0_bits_data <= io_dma_w_data_i_bits_data;
    dma_w_data_i_reg_0_bits_length <= io_dma_w_data_i_bits_length;
    dma_w_data_i_reg_0_bits_port <= io_dma_w_data_i_bits_port;
    dma_w_data_i_reg_1_bits_pcie_write_addr <= dma_w_data_i_reg_0_bits_pcie_write_addr;
    dma_w_data_i_reg_1_bits_data <= dma_w_data_i_reg_0_bits_data;
    dma_w_data_i_reg_1_bits_length <= dma_w_data_i_reg_0_bits_length;
    dma_w_data_i_reg_1_bits_port <= dma_w_data_i_reg_0_bits_port;
    dma_w_data_i_reg_0_valid <= io_dma_w_data_i_valid;
    dma_w_data_i_reg_1_valid <= dma_w_data_i_reg_0_valid;
    dma_r_req_i_reg_0_bits_pcie_read_addr <= io_dma_r_req_i_bits_pcie_read_addr;
    dma_r_req_i_reg_0_bits_cache_id <= io_dma_r_req_i_bits_cache_id;
    dma_r_req_i_reg_0_bits_message_size <= io_dma_r_req_i_bits_message_size;
    dma_r_req_i_reg_0_bits_read_len <= io_dma_r_req_i_bits_read_len;
    dma_r_req_i_reg_0_bits_dest_ram_addr <= io_dma_r_req_i_bits_dest_ram_addr;
    dma_r_req_i_reg_0_bits_port <= io_dma_r_req_i_bits_port;
    dma_r_req_i_reg_1_bits_pcie_read_addr <= dma_r_req_i_reg_0_bits_pcie_read_addr;
    dma_r_req_i_reg_1_bits_cache_id <= dma_r_req_i_reg_0_bits_cache_id;
    dma_r_req_i_reg_1_bits_message_size <= dma_r_req_i_reg_0_bits_message_size;
    dma_r_req_i_reg_1_bits_read_len <= dma_r_req_i_reg_0_bits_read_len;
    dma_r_req_i_reg_1_bits_dest_ram_addr <= dma_r_req_i_reg_0_bits_dest_ram_addr;
    dma_r_req_i_reg_1_bits_port <= dma_r_req_i_reg_0_bits_port;
    dma_r_req_i_reg_0_valid <= io_dma_r_req_i_valid;
    dma_r_req_i_reg_1_valid <= dma_r_req_i_reg_0_valid;
    new_dma_map_i_reg_0_bits_pcie_addr <= io_new_dma_map_i_bits_pcie_addr;
    new_dma_map_i_reg_0_bits_port <= io_new_dma_map_i_bits_port;
    new_dma_map_i_reg_0_bits_map_type <= io_new_dma_map_i_bits_map_type;
    new_dma_map_i_reg_0_valid <= io_new_dma_map_i_valid;
  end // always @(posedge)
  mem_16384x82 h2c_data_maps_ext (
    .R0_addr (dma_r_req_i_reg_0_bits_port[13:0]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_h2c_data_maps_ext_R0_data),
    .W0_addr (new_dma_map_i_reg_0_bits_port[13:0]),
    .W0_en   (new_dma_map_i_reg_0_valid & _GEN_0),
    .W0_clk  (clock),
    .W0_data (_GEN)
  );
  mem_16384x82 c2h_data_maps_ext (
    .R0_addr (dma_w_data_i_reg_0_bits_port[13:0]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_c2h_data_maps_ext_R0_data),
    .W0_addr (new_dma_map_i_reg_0_bits_port[13:0]),
    .W0_en   (new_dma_map_i_reg_0_valid & ~_GEN_0 & _GEN_1),
    .W0_clk  (clock),
    .W0_data (_GEN)
  );
  mem_16384x82 metadata_maps_ext (
    .R0_addr (dma_w_meta_i_reg_0_bits_port[13:0]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_metadata_maps_ext_R0_data),
    .W0_addr (new_dma_map_i_reg_0_bits_port[13:0]),
    .W0_en
      (new_dma_map_i_reg_0_valid & ~(_GEN_0 | _GEN_1)
       & new_dma_map_i_reg_0_bits_map_type == 2'h2),
    .W0_clk  (clock),
    .W0_data (_GEN)
  );
  assign io_new_dma_map_i_ready = 1'h1;
  assign io_dma_w_meta_i_ready = 1'h1;
  assign io_dma_w_data_i_ready = 1'h1;
  assign io_dma_r_req_i_ready = 1'h1;
  assign io_dma_w_req_o_valid = dma_w_meta_i_reg_1_valid | dma_w_data_i_reg_1_valid;
  assign io_dma_w_req_o_bits_pcie_write_addr =
    dma_w_meta_i_reg_1_valid
      ? _metadata_maps_ext_R0_data[63:0] + dma_w_meta_i_reg_1_bits_pcie_write_addr
      : dma_w_data_i_reg_1_valid
          ? _c2h_data_maps_ext_R0_data[63:0] + dma_w_data_i_reg_1_bits_pcie_write_addr
          : 64'h0;
  assign io_dma_w_req_o_bits_data =
    dma_w_meta_i_reg_1_valid
      ? dma_w_meta_i_reg_1_bits_data
      : dma_w_data_i_reg_1_valid ? dma_w_data_i_reg_1_bits_data : 512'h0;
  assign io_dma_w_req_o_bits_length =
    dma_w_meta_i_reg_1_valid
      ? dma_w_meta_i_reg_1_bits_length
      : dma_w_data_i_reg_1_valid ? dma_w_data_i_reg_1_bits_length : 8'h0;
  assign io_dma_w_req_o_bits_port =
    dma_w_meta_i_reg_1_valid
      ? dma_w_meta_i_reg_1_bits_port
      : dma_w_data_i_reg_1_valid ? dma_w_data_i_reg_1_bits_port : 16'h0;
  assign io_dma_r_req_o_valid = dma_r_req_i_reg_1_valid;
  assign io_dma_r_req_o_bits_pcie_read_addr =
    dma_r_req_i_reg_1_valid
      ? _h2c_data_maps_ext_R0_data[63:0] + dma_r_req_i_reg_1_bits_pcie_read_addr
      : 64'h0;
  assign io_dma_r_req_o_bits_cache_id =
    dma_r_req_i_reg_1_valid ? dma_r_req_i_reg_1_bits_cache_id : 10'h0;
  assign io_dma_r_req_o_bits_message_size =
    dma_r_req_i_reg_1_valid ? dma_r_req_i_reg_1_bits_message_size : 20'h0;
  assign io_dma_r_req_o_bits_read_len =
    dma_r_req_i_reg_1_valid ? dma_r_req_i_reg_1_bits_read_len : 12'h0;
  assign io_dma_r_req_o_bits_dest_ram_addr =
    dma_r_req_i_reg_1_valid ? dma_r_req_i_reg_1_bits_dest_ram_addr : 20'h0;
  assign io_dma_r_req_o_bits_port =
    dma_r_req_i_reg_1_valid ? dma_r_req_i_reg_1_bits_port : 16'h0;
endmodule

