// Generated by CIRCT firtool-1.62.0
// VCS coverage exclude_file
module tag_mem_256x42(
  input  [7:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [41:0] R0_data,
  input  [7:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [41:0] W0_data
);

  reg [41:0] Memory[0:255];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 42'bx;
endmodule

module h2c_dma(
  input         clock,
                reset,
  output        io_dma_read_req_i_ready,
  input         io_dma_read_req_i_valid,
  input  [63:0] io_dma_read_req_i_bits_pcie_read_addr,
  input  [9:0]  io_dma_read_req_i_bits_cache_id,
  input  [19:0] io_dma_read_req_i_bits_message_size,
  input  [11:0] io_dma_read_req_i_bits_read_len,
  input  [19:0] io_dma_read_req_i_bits_dest_ram_addr,
  input  [15:0] io_dma_read_req_i_bits_port,
  input         io_pcie_read_cmd_o_ready,
  output        io_pcie_read_cmd_o_valid,
  output [63:0] io_pcie_read_cmd_o_bits_pcie_read_addr,
  output [1:0]  io_pcie_read_cmd_o_bits_dest_ram_sel,
  output [17:0] io_pcie_read_cmd_o_bits_dest_ram_addr,
  output [15:0] io_pcie_read_cmd_o_bits_read_len,
  output [7:0]  io_pcie_read_cmd_o_bits_tag,
  output        io_pcie_read_status_i_ready,
  input         io_pcie_read_status_i_valid,
  input  [7:0]  io_pcie_read_status_i_bits_tag,
  input  [3:0]  io_pcie_read_status_i_bits_error,
  input         io_dbuff_notif_o_ready,
  output        io_dbuff_notif_o_valid,
  output [15:0] io_dbuff_notif_o_bits_rpc_id,
  output [9:0]  io_dbuff_notif_o_bits_cache_id,
  output [19:0] io_dbuff_notif_o_bits_remaining_bytes,
                io_dbuff_notif_o_bits_dbuffered_bytes,
                io_dbuff_notif_o_bits_granted_bytes,
  output [2:0]  io_dbuff_notif_o_bits_priority
);

  wire [41:0] _tag_mem_ext_R0_data;
  reg  [7:0]  tag;
  always @(posedge clock) begin
    if (reset)
      tag <= 8'h0;
    else if (io_dma_read_req_i_valid)
      tag <= tag + 8'h1;
  end // always @(posedge)
  tag_mem_256x42 tag_mem_ext (
    .R0_addr (io_pcie_read_status_i_bits_tag),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_tag_mem_ext_R0_data),
    .W0_addr (tag),
    .W0_en   (io_dma_read_req_i_valid),
    .W0_clk  (clock),
    .W0_data
      ({io_dma_read_req_i_bits_dest_ram_addr,
        io_dma_read_req_i_bits_read_len,
        io_dma_read_req_i_bits_cache_id})
  );
  assign io_dma_read_req_i_ready = io_pcie_read_cmd_o_ready;
  assign io_pcie_read_cmd_o_valid = io_dma_read_req_i_valid;
  assign io_pcie_read_cmd_o_bits_pcie_read_addr = io_dma_read_req_i_bits_pcie_read_addr;
  assign io_pcie_read_cmd_o_bits_dest_ram_sel = 2'h0;
  assign io_pcie_read_cmd_o_bits_dest_ram_addr =
    io_dma_read_req_i_bits_dest_ram_addr[17:0];
  assign io_pcie_read_cmd_o_bits_read_len = {4'h0, io_dma_read_req_i_bits_read_len};
  assign io_pcie_read_cmd_o_bits_tag = tag;
  assign io_pcie_read_status_i_ready = io_dbuff_notif_o_ready;
  assign io_dbuff_notif_o_valid = io_pcie_read_status_i_valid;
  assign io_dbuff_notif_o_bits_rpc_id = 16'h0;
  assign io_dbuff_notif_o_bits_cache_id = _tag_mem_ext_R0_data[9:0];
  assign io_dbuff_notif_o_bits_remaining_bytes =
    {8'h0, _tag_mem_ext_R0_data[21:10]} - _tag_mem_ext_R0_data[41:22] - 20'h100;
  assign io_dbuff_notif_o_bits_dbuffered_bytes = 20'h0;
  assign io_dbuff_notif_o_bits_granted_bytes = 20'h0;
  assign io_dbuff_notif_o_bits_priority = 3'h1;
endmodule

