Simulation:
  competitions: 100000

Host:
  Rates:
    - {rate: .9, size: 1, token: "RPC", dist: "Poisson"}

  Queue:
    # 1 unit is 64 bytes
    # If a write takes 700ns from host, and timestep is 5ns, then 140 cycle comm delay
    # Rough priority queue latency https://gcc.gnu.org/onlinedocs/libstdc++/ext/pb_ds/priority_queue_text_push_timing_test.html
    commDelay: 140
    queueDelay: 40
    # onChipDepth: 10000
    onChipDepth: 10
    offChipDepth: 10000
